app = "facebook-bayers"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8080"
  LOG_TO_STDOUT = "1"
  PYTHONUNBUFFERED = "1"

[mounts]
  source = "facebook_bayers_data"
  destination = "/data"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]
