app = "facebook-bayers"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8080"
  LOG_TO_STDOUT = "1"
  DATABASE_URL = "sqlite:////data/app.db"

[mounts]
  source = "facebook_bayers_data"
  destination = "/data"

[[services]]
  protocol = "tcp"
  internal_port = 8080
  
  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80
  
  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
  
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.tcp_checks]]
    grace_period = "20s"
    interval = "15s"
    restart_limit = 0
    timeout = "5s" 