"""Add check_period field to Setup model

Revision ID: 23e1544a7c55
Revises: 8fd5680c3c8e
Create Date: 2025-04-16 14:52:25.666027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23e1544a7c55'
down_revision = '8fd5680c3c8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('setups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('check_period', sa.String(length=20), nullable=True))
    
    # Заполнить существующие записи значением по умолчанию "today"
    op.execute("UPDATE setups SET check_period = 'today' WHERE check_period IS NULL")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('setups', schema=None) as batch_op:
        batch_op.drop_column('check_period')

    # ### end Alembic commands ###
