"""add conversions model

Revision ID: 40c4de07e099
Revises: 3853d5e09725
Create Date: 2025-04-14 13:51:24.006026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40c4de07e099'
down_revision = '3853d5e09725'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ref', sa.String(length=255), nullable=True),
    sa.Column('ref_prefix', sa.String(length=3), nullable=True),
    sa.Column('form_id', sa.String(length=50), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversions_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversions_form_id'), ['form_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversions_ref'), ['ref'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversions_ref_prefix'), ['ref_prefix'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversions_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversions_timestamp'))
        batch_op.drop_index(batch_op.f('ix_conversions_ref_prefix'))
        batch_op.drop_index(batch_op.f('ix_conversions_ref'))
        batch_op.drop_index(batch_op.f('ix_conversions_form_id'))
        batch_op.drop_index(batch_op.f('ix_conversions_date'))

    op.drop_table('conversions')
    # ### end Alembic commands ###
