"""Initial migration

Revision ID: 53998c57c348
Revises: 
Create Date: 2025-03-10 17:21:59.100852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53998c57c348'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('fb_access_token', sa.String(length=255), nullable=True),
    sa.Column('fb_app_id', sa.String(length=50), nullable=True),
    sa.Column('fb_app_secret', sa.String(length=100), nullable=True),
    sa.Column('fb_account_id', sa.String(length=50), nullable=True),
    sa.Column('active_token_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('facebook_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('access_token', sa.String(length=255), nullable=False),
    sa.Column('app_id', sa.String(length=50), nullable=True),
    sa.Column('app_secret', sa.String(length=100), nullable=True),
    sa.Column('use_proxy', sa.Boolean(), nullable=True),
    sa.Column('proxy_url', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('last_checked', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('setups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('check_interval', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('campaign_setups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('setup_id', sa.Integer(), nullable=True),
    sa.Column('campaign_id', sa.String(length=50), nullable=False),
    sa.Column('campaign_name', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_checked', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['setup_id'], ['setups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('facebook_token_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_id', sa.Integer(), nullable=True),
    sa.Column('account_id', sa.String(length=50), nullable=False),
    sa.Column('account_name', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_checked', sa.DateTime(), nullable=True),
    sa.Column('campaign_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['token_id'], ['facebook_tokens.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('threshold_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('setup_id', sa.Integer(), nullable=True),
    sa.Column('spend', sa.Float(), nullable=False),
    sa.Column('conversions', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['setup_id'], ['setups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('threshold_entries')
    op.drop_table('facebook_token_accounts')
    op.drop_table('campaign_setups')
    op.drop_table('setups')
    op.drop_table('facebook_tokens')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
