"""Update FacebookToken model with use_proxy flag and optional fields

Revision ID: 72b9537e6a4b
Revises: 036b99725ffe
Create Date: 2025-03-08 00:46:56.630963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72b9537e6a4b'
down_revision = '036b99725ffe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('facebook_tokens', sa.Column('use_proxy', sa.Boolean(), nullable=True))
    op.add_column('facebook_tokens', sa.Column('account_names', sa.Text(), nullable=True))
    op.add_column('facebook_tokens', sa.Column('campaign_count', sa.Integer(), nullable=True))
    op.alter_column('facebook_tokens', 'app_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('facebook_tokens', 'app_secret',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('facebook_tokens', 'account_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=500),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('facebook_tokens', 'account_id',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('facebook_tokens', 'app_secret',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('facebook_tokens', 'app_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_column('facebook_tokens', 'campaign_count')
    op.drop_column('facebook_tokens', 'account_names')
    op.drop_column('facebook_tokens', 'use_proxy')
    # ### end Alembic commands ###
