"""add quid field to conversion model

Revision ID: 8fd5680c3c8e
Revises: 40c4de07e099
Create Date: 2025-04-14 18:32:14.950600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fd5680c3c8e'
down_revision = '40c4de07e099'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quid', sa.String(length=100), nullable=True))
        batch_op.create_index(batch_op.f('ix_conversions_quid'), ['quid'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversions_quid'))
        batch_op.drop_column('quid')

    # ### end Alembic commands ###
