"""add user admin 2fa fields

Revision ID: 3a5f73a4bc12
Revises: 23e1544a7c55
Create Date: 2025-04-16 20:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a5f73a4bc12'
down_revision = '23e1544a7c55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('totp_secret', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('is_2fa_enabled', sa.Boolean(), nullable=True))
    
    # Устанавливаем значения по умолчанию для существующих записей
    op.execute("UPDATE users SET is_admin = 0 WHERE is_admin IS NULL")
    op.execute("UPDATE users SET is_2fa_enabled = 0 WHERE is_2fa_enabled IS NULL")
    
    # Установить первого пользователя как администратора
    op.execute("UPDATE users SET is_admin = 1 WHERE id = 1")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_2fa_enabled')
        batch_op.drop_column('totp_secret')
        batch_op.drop_column('is_admin')
    # ### end Alembic commands ### 